### ISSUE TITLE
Not working on 1.38

### ISSUE THREAD

**Issue by btx-systems** [btx-systems/MultiplayerNameChanger#1]
The mod does not work on the latest version

**Comment by sizzlefly** [comment]
Thank you for actually working on 1.38.0 port! For some reason multiplayer on 1.37.3 was giving me insane lag, and 38 is much more optimized! Thank you!!

**Comment by btx-systems** [comment]
I have created a new release with a version working on [1.38](https://github.com/btx-systems/MultiplayerNameChanger/releases/tag/0.0.6)

I don't play Beat Saber very much anymore so please let me know if the mod stops working again

**Comment by sizzlefly** [comment]
You got it :)
